### ISSUE TITLE
THIS IS MALICIOUS | OVER 50 FLAGS | NOT OPEN SOURCE.

### ISSUE THREAD

**Issue by LimitedJokes** [iMewIRL/Rupture#1]
This is not open source idk why its on github and also has over 50 flags. I don't recommend running this file.

**Comment by iMewIRL** [comment]
It's exe file because the whole source code is obfuscated, it also uses Themida from Orean Technologies so you can maybe look into that why some certain factors can make the program detected by a few antiviruses. If you could show me a discord-based tool like this that has similar functions please show me how it is not detected by anything ;)
